name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no \
        ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
        'cd /path/to/project && git pull && npm install && npm run build && pm2 start npm --name "project_name" -- start'
